version: '3'
networks:
  internal-network:
    driver: bridge

services:

  #RabbitMQ service.
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    labels:
      kompose.service.type: nodeport
    ports:
    - '4369:4369'
    - '5672:5672'
    - '25672:25672'
    - '15672:15672'
    volumes:
    - 'rabbitmq_data:/bitnami'

volumes:
  data-volume:
  rabbitmq_data:
    driver: local